'use client';
import { useState } from 'react';
import { Clock, Plus, Trash2, Check } from 'lucide-react';
export function lagosDate() { return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
function now() { return new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()); }
type Person = {name:string;status:'PRESENT'|'ABSENT'|'LATE';arrivalTime:string;departureTime:string};
const person = ():Person => ({name:'',status:'PRESENT',arrivalTime:'',departureTime:''});
export default function LogSession({onSaved}:{onSaved:()=>void}) {
 const [people,setPeople]=useState<Person[]>([person()]);const [arrival,setArrival]=useState('');const [departure,setDeparture]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);
 const update=(i:number,patch:Partial<Person>)=>setPeople(p=>p.map((a,j)=>j===i?{...a,...patch}:a));
 return <form className="card" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setSuccess(false);const f=new FormData(form);try{const r=await fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({school:f.get('school'),date:f.get('date'),week:Number(f.get('week')),arrivalTime:arrival,departureTime:departure,topic:f.get('topic'),attendance:people})});const d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();setPeople([person()]);setArrival('');setDeparture('');setSuccess(true);onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}}>
 <div className="px-6 py-5 border-b border-slate-100"><h2 className="text-lg font-semibold">Session details</h2><p className="text-sm text-slate-500 mt-1">Record your class and the learning covered. Times use Africa/Lagos.</p></div>
 <fieldset disabled={busy} className="p-6 space-y-6"><div className="grid sm:grid-cols-2 gap-5"><div><label htmlFor="school" className="label">Name of school <span className="text-lagos-red">*</span></label><input id="school" name="school" className="field" placeholder="e.g. Lagos City Secondary School" minLength={2} maxLength={150} required/></div><div className="grid grid-cols-2 gap-4"><div><label htmlFor="date" className="label">Session date *</label><input id="date" name="date" type="date" className="field" defaultValue={lagosDate()} required/></div><div><label htmlFor="week" className="label">Academic week *</label><input id="week" name="week" type="number" min={1} max={53} defaultValue={1} className="field" required/></div></div></div>
 <div className="grid sm:grid-cols-2 gap-5"><div><label htmlFor="arrival" className="label">Arrival / start time *</label><div className="flex gap-2"><input id="arrival" type="time" className="field" value={arrival} onChange={e=>setArrival(e.target.value)} required/><button type="button" className="secondary whitespace-nowrap" onClick={()=>setArrival(now())}><Clock size={15}/>Clock in</button></div></div><div><label htmlFor="departure" className="label">Departure / end time</label><div className="flex gap-2"><input id="departure" type="time" className="field" value={departure} onChange={e=>setDeparture(e.target.value)}/><button type="button" className="secondary whitespace-nowrap" onClick={()=>setDeparture(now())}><Clock size={15}/>Clock out</button></div></div></div>
 <div><label htmlFor="topic" className="label">Topic taught *</label><textarea id="topic" name="topic" className="field min-h-28" placeholder="Describe the subject, key concepts and activities covered…" minLength={3} maxLength={5000} required/></div>
 <div className="border-t pt-6"><div className="flex justify-between items-center gap-3 mb-4"><div><h3 className="font-semibold">Participant attendance</h3><p className="text-sm text-slate-500">Add each participant, including absentees.</p></div><button type="button" className="secondary" disabled={people.length>=500} onClick={()=>setPeople(p=>[...p,person()])}><Plus size={16}/>Add</button></div>
 <div className="space-y-3">{people.map((p,i)=><div key={i} className="grid sm:grid-cols-[2fr_1fr_1fr_1fr_auto] gap-3 rounded-lg bg-slate-50 p-3 items-end"><div><label className="label" htmlFor={`name-${i}`}>Participant {i+1}</label><input id={`name-${i}`} className="field" placeholder="Full name" value={p.name} minLength={2} maxLength={120} required onChange={e=>update(i,{name:e.target.value})}/></div><div><label className="label" htmlFor={`status-${i}`}>Status</label><select id={`status-${i}`} className="field" value={p.status} onChange={e=>update(i,{status:e.target.value as Person['status'],...(e.target.value==='ABSENT'?{arrivalTime:'',departureTime:''}:{})})}><option value="PRESENT">Present</option><option value="LATE">Late</option><option value="ABSENT">Absent</option></select></div><div><label className="label" htmlFor={`in-${i}`}>Arrival</label><input id={`in-${i}`} type="time" className="field" disabled={p.status==='ABSENT'} value={p.arrivalTime} onChange={e=>update(i,{arrivalTime:e.target.value})}/></div><div><label className="label" htmlFor={`out-${i}`}>Departure</label><input id={`out-${i}`} type="time" className="field" disabled={p.status==='ABSENT'} value={p.departureTime} onChange={e=>update(i,{departureTime:e.target.value})}/></div><button type="button" className="secondary" aria-label={`Remove participant ${i+1}`} disabled={people.length===1} onClick={()=>setPeople(p=>p.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}</div></div>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{success&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-lagos-green">Session and attendance saved successfully.</p>}
 <div className="flex flex-wrap justify-between gap-4 items-center border-t pt-5"><p className="text-xs text-slate-500">* Required fields · Sessions start and end on the same day.</p><button className="primary" disabled={busy}><Check size={17}/>{busy?'Saving…':'Save session'}</button></div></fieldset></form>;
}
