'use client';
import { useEffect, useState, useCallback } from 'react';
import { GraduationCap, LayoutDashboard, ClipboardList, History, LogOut, Plus, Users, BookOpen, CheckCircle2, Clock, ArrowRight, Download, CalendarDays } from 'lucide-react';
import LogSession, { lagosDate } from './log-session';
type RecordRow = {id:string;date:string;week:number;arrivalTime:string;departureTime:string|null;topic:string;school:{name:string};attendance:{status:string;arrivalTime:string|null;departureTime:string|null;participant:{name:string}}[]};
type Data = {sessions:RecordRow[];total:number;pageSize:number;stats:{sessionCount:number;counts:{status:string;_count:{_all:number}}[];todaySessions:RecordRow[]}};
const tabs=[{name:'Dashboard',icon:LayoutDashboard},{name:'Log session',icon:ClipboardList},{name:'History & reports',icon:History}];
function displayDate(date:string) { return new Date(date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}); }
function count(s:RecordRow,status:string) { return s.attendance.filter(a=>a.status===status).length; }
function csvCell(value:unknown) { const s=String(value??''); return '"'+(/^[\s]*[=+@\-]|^[\t\r\n]/.test(s)?"'"+s:s).replaceAll('"','""')+'"'; }
export default function Workspace() {
 const [tab,setTab]=useState('Dashboard'); const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [week,setWeek]=useState('');const [date,setDate]=useState('');const [page,setPage]=useState(1);const [exporting,setExporting]=useState(false);const [selected,setSelected]=useState<RecordRow|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({page:String(page)});if(week)p.set('week',week);if(date)p.set('date',date);const r=await fetch('/api/sessions?'+p);if(r.status===401){window.location.href='/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Could not load sessions');}finally{setLoading(false);}},[week,date,page]);
 useEffect(()=>{void load();},[load]);
 const stats=data?.stats;const present=stats?.counts.find(c=>c.status==='PRESENT')?._count._all??0;const late=stats?.counts.find(c=>c.status==='LATE')?._count._all??0;const absent=stats?.counts.find(c=>c.status==='ABSENT')?._count._all??0;const total=present+late+absent;
 const today=stats?.todaySessions??[];
 const cards=[{label:'Total sessions',value:stats?.sessionCount??0,sub:'Across all recorded schools',icon:BookOpen,color:'text-lagos-blue bg-blue-50'},{label:'Attendance rate',value:total?Math.round((present+late)/total*100)+'%':'—',sub:'Present and late / all entries',icon:CheckCircle2,color:'text-lagos-green bg-green-50'},{label:'Attendance entries',value:total,sub:`${present} present · ${absent} absent`,icon:Users,color:'text-lagos-blue bg-blue-50'},{label:'Late arrivals',value:late,sub:'Across all recorded sessions',icon:Clock,color:'text-amber-700 bg-amber-50'}];
 const records=tab==='Dashboard'?data?.sessions.slice(0,5):data?.sessions;
 async function exportCsv() {setExporting(true);setError('');try{const rows:RecordRow[]=[];let current=1;let totalRows=Infinity;while(rows.length<totalRows){const p=new URLSearchParams({page:String(current)});if(week)p.set('week',week);if(date)p.set('date',date);const r=await fetch('/api/sessions?'+p);const d=await r.json();if(!r.ok)throw new Error(d.error);rows.push(...d.sessions);totalRows=d.total;if(!d.sessions.length)break;current++;}const csv=[['School','Date','Week','Session arrival','Session departure','Topic','Participant','Status','Participant arrival','Participant departure'],...rows.flatMap(s=>s.attendance.map(a=>[s.school.name,s.date.slice(0,10),s.week,s.arrivalTime,s.departureTime,s.topic,a.participant.name,a.status,a.arrivalTime,a.departureTime]))].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`attendance-${lagosDate()}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'Export failed');}finally{setExporting(false);}}
 return <div className="min-h-screen lg:flex"><aside className="lg:w-64 lg:fixed lg:inset-y-0 bg-white border-r border-slate-200 flex flex-col"><div className="px-6 py-7 flex items-center gap-3"><div className="rounded-xl bg-lagos-green p-2.5 text-white"><GraduationCap size={26}/></div><div><p className="font-bold text-xl tracking-tight">ClassLedger</p><p className="text-[10px] font-semibold tracking-widest text-slate-400">ATTENDANCE & LEARNING</p></div></div><div className="mx-6 flex h-1 rounded overflow-hidden"><span className="bg-lagos-green w-1/4"/><span className="bg-lagos-yellow w-1/4"/><span className="bg-lagos-red w-1/4"/><span className="bg-lagos-blue w-1/4"/></div><p className="hidden lg:block text-xs text-slate-400 font-semibold px-7 mt-9 mb-3">WORKSPACE</p><nav className="flex lg:flex-col p-3 gap-2 overflow-x-auto">{tabs.map(t=><button key={t.name} onClick={()=>{setTab(t.name);setSelected(null);setWeek('');setDate('');setPage(1);}} className={`flex items-center gap-3 px-4 py-3 rounded-lg text-sm whitespace-nowrap ${tab===t.name?'bg-green-50 text-lagos-green font-semibold':'text-slate-500 hover:bg-slate-50'}`}><t.icon size={19}/>{t.name}</button>)}</nav><div className="hidden lg:block mt-auto p-6"><div className="bg-slate-50 rounded-lg p-4"><p className="text-sm font-semibold">Every class counts.</p><p className="text-xs leading-5 text-slate-500 mt-2">A clear record of attendance and learning, one session at a time.</p></div><div className="flex items-center gap-3 mt-6"><span className="bg-green-100 text-lagos-green rounded-full h-9 w-9 flex items-center justify-center font-semibold">A</span><div className="flex-1"><p className="text-sm font-semibold">Administrator</p><p className="text-xs text-slate-400">School workspace</p></div><button aria-label="Sign out" onClick={async()=>{await fetch('/api/logout',{method:'POST'});window.location.href='/login';}}><LogOut size={18}/></button></div></div></aside>
 <div className="lg:ml-64 flex-1 min-w-0"><header className="h-20 bg-white border-b flex items-center justify-between px-6 sm:px-10"><p className="text-sm text-slate-500">Workspace <span className="mx-2 text-slate-300">/</span><span className="text-slate-800 font-medium">{tab}</span></p><div className="flex gap-3 items-center"><span className="hidden sm:flex items-center gap-2 text-sm text-slate-500"><CalendarDays size={16}/>{displayDate(lagosDate())}</span><button className="lg:hidden secondary" aria-label="Sign out" onClick={async()=>{await fetch('/api/logout',{method:'POST'});window.location.href='/login';}}><LogOut size={16}/></button></div></header>
 <main className="p-5 sm:p-10 max-w-7xl mx-auto"><div className="flex flex-wrap gap-4 items-center justify-between mb-8"><div><p className="uppercase tracking-widest text-[11px] font-bold text-lagos-green mb-2">School attendance & curriculum</p><h1 className="text-3xl font-bold tracking-tight">{tab==='Dashboard'?'Your classes, at a glance.':tab==='Log session'?'Log a new session':'History & reports'}</h1><p className="text-slate-500 mt-2 text-sm">{tab==='Dashboard'?'Stay on top of attendance and keep learning moving.':tab==='Log session'?'Capture attendance and what your class learned today.':'Explore your past sessions and download attendance records.'}</p></div>{tab!=='Log session'&&<button className="primary" onClick={()=>setTab('Log session')}><Plus size={18}/>Log session</button>}</div>
 {error&&<div role="alert" className="bg-red-50 border border-red-100 rounded-lg p-4 mb-6 text-red-700 text-sm">{error} <button className="underline ml-2" onClick={()=>void load()}>Retry</button></div>}
 {tab==='Log session'?<LogSession onSaved={()=>void load()}/>:<>{tab==='Dashboard'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-7">{cards.map(c=><div key={c.label} className="card p-5"><div className="flex justify-between items-center"><p className="text-sm text-slate-500">{c.label}</p><span className={`p-2 rounded-lg ${c.color}`}><c.icon size={18}/></span></div><p className="text-3xl font-bold mt-3">{loading?'…':error?'—':c.value}</p><p className="text-xs text-slate-400 mt-2">{c.sub}</p></div>)}</div><div className="rounded-xl bg-lagos-green text-white p-6 sm:p-8 mb-8 relative overflow-hidden"><span className="absolute w-48 h-48 border-[30px] border-white/5 rounded-full -right-5 -top-10"/><p className="uppercase text-xs tracking-widest text-green-200 font-semibold">Today’s classes</p>{today.length?<div className="space-y-4 mt-4">{today.map(s=><button key={s.id} onClick={()=>setSelected(s)} className="block text-left relative"><h2 className="font-semibold text-xl">{s.topic}</h2><p className="text-green-100 text-sm mt-2">{s.school.name} · Week {s.week} · {s.arrivalTime} – {s.departureTime??'In progress'} · {count(s,'PRESENT')+count(s,'LATE')} attending</p></button>)}</div>:<><h2 className="font-semibold text-2xl mt-3">{loading?'Loading today’s classes…':'A new day of learning.'}</h2><p className="text-green-100 text-sm mt-2">{error?'Connect the database to see today’s classes.':'No sessions recorded for today yet. Start with your first class.'}</p></>}<button onClick={()=>setTab('Log session')} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold relative">Record a session <ArrowRight size={16}/></button></div></>}
 <div className="card overflow-hidden"><div className="p-5 flex flex-wrap gap-4 justify-between items-center border-b"><div><h2 className="font-semibold">{tab==='Dashboard'?'Recent sessions':'Session records'}</h2><p className="text-xs text-slate-500 mt-1">{tab==='Dashboard'?'Your latest attendance and teaching records':`${data?.total??0} sessions matching your filters`}</p></div>{tab==='Dashboard'?<button className="text-sm text-lagos-green font-semibold" onClick={()=>setTab('History & reports')}>View all records →</button>:<button className="secondary" disabled={exporting||loading||Boolean(error)||!data?.total} onClick={()=>void exportCsv()}><Download size={16}/>{exporting?'Exporting…':'Export CSV'}</button>}</div>
 {tab!=='Dashboard'&&<div className="p-5 flex flex-wrap gap-4 items-end bg-slate-50"><div><label htmlFor="filterWeek" className="label">Academic week</label><select id="filterWeek" className="field" value={week} onChange={e=>{setWeek(e.target.value);setPage(1);}}><option value="">All weeks</option>{Array.from({length:53},(_,i)=><option key={i} value={i+1}>Week {i+1}</option>)}</select></div><div><label htmlFor="filterDate" className="label">Session date</label><input id="filterDate" className="field" type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);}}/></div><button className="secondary" onClick={()=>{setWeek('');setDate('');setPage(1);}}>Clear filters</button></div>}
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500 text-xs"><tr>{['School & topic','Date / week','Session time','Attendance','Details'].map(h=><th key={h} className="px-5 py-4 font-medium">{h}</th>)}</tr></thead><tbody>{!loading&&!error&&records?.map(s=><tr key={s.id} className="border-t hover:bg-slate-50"><td className="px-5 py-4 min-w-56 max-w-xs"><p className="font-medium">{s.school.name}</p><p className="text-slate-500 text-xs mt-1 truncate">{s.topic}</p></td><td className="px-5 py-4 whitespace-nowrap">{displayDate(s.date)}<p className="text-xs text-slate-400 mt-1">Week {s.week}</p></td><td className="px-5 py-4 whitespace-nowrap text-slate-500">{s.arrivalTime} – {s.departureTime??'Open'}</td><td className="px-5 py-4"><div className="flex gap-2 whitespace-nowrap"><span className="bg-green-50 text-lagos-green rounded px-2 py-1 text-xs">{count(s,'PRESENT')} present</span><span className="bg-amber-50 text-amber-700 rounded px-2 py-1 text-xs">{count(s,'LATE')} late</span><span className="bg-red-50 text-red-700 rounded px-2 py-1 text-xs">{count(s,'ABSENT')} absent</span></div></td><td className="px-5 py-4"><button className="text-lagos-green font-medium" onClick={()=>setSelected(s)}>View</button></td></tr>)}</tbody></table></div>{(loading||error||!records?.length)&&<div className="text-center py-14 px-5"><ClipboardList className="text-slate-300 mx-auto mb-3" size={32}/><p className="font-medium">{loading?'Loading sessions…':error?'Records unavailable':'No sessions found'}</p><p className="text-sm text-slate-400 mt-2">{error?'Resolve the connection error above to load your records.':'Log a session or adjust your filters to see records here.'}</p></div>}
 {tab!=='Dashboard'&&data&&data.total>50&&<div className="p-4 border-t flex justify-between items-center"><button className="secondary" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm text-slate-500">Page {page} of {Math.ceil(data.total/50)}</span><button className="secondary" disabled={page*50>=data.total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</div></>}
 {selected&&<section className="card mt-6 p-6" aria-label="Session details"><div className="flex justify-between gap-4"><h2 className="font-semibold text-xl">{selected.school.name}</h2><button className="secondary" onClick={()=>setSelected(null)}>Close details</button></div><p className="text-sm text-slate-500 mt-2">{displayDate(selected.date)} · Week {selected.week} · {selected.arrivalTime} – {selected.departureTime??'Open'}</p><p className="whitespace-pre-wrap my-5">{selected.topic}</p><ul className="divide-y">{selected.attendance.map((a,i)=><li className="py-3 flex flex-wrap justify-between gap-2 text-sm" key={i}><span>{a.participant.name}</span><span className="text-slate-500">{a.status.toLowerCase()} · {a.arrivalTime??'—'} – {a.departureTime??'—'}</span></li>)}</ul></section>}
 <footer className="mt-10 flex justify-between text-xs text-slate-400"><span>ClassLedger · Built for better learning</span><span>Lagos, Nigeria · WAT</span></footer></main></div></div>;
}
